# Allow Thymeleaf templates to be reloaded at dev time
spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
  #PROD
  datasource:
    url: jdbc:mysql://localhost:3306/messagedb?serverTimezone=UTC
    username: root
    password: aaaa
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf.cache: false
#Embedded
#  datasource:
#    url: jdbc:h2:file:~/test
#    username: sa
#    password: sa
#    driver-class-name: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

server:
  tomcat:
    access_log_enabled: true
    basedir: target/tomcat

logging.level:
#  org.hibernate.SQL: DEBUG
  sample.web.ui: DEBUG
